DROP DATABASE HR;
CREATE DATABASE HR;
USE HR;
CREATE TABLE EMPLOYEES (
EMPLOYEE_ID	INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(30),
LAST_NAME VARCHAR(30),
EMAIL VARCHAR(50),
PHONE_NUMBER INT UNSIGNED,
HIRE_DATE DATE,
JOB_ID INT UNSIGNED,
SALARY DECIMAL(10,2),
COMMISSION_PCT DECIMAL(10,2),
MANAGER_ID INT UNSIGNED, 
DEPARTMENT_ID INT UNSIGNED
);
CREATE TABLE DEPARTMENTS (
DEPARTMENT_ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
MANAGER_ID INT UNSIGNED,
LOCATION_ID INT UNSIGNED
);
CREATE TABLE JOBS (
JOB_ID INT UNSIGNED PRIMARY KEY,
JOB_TITLE VARCHAR(30),
MIN_SALARY DECIMAL(6,2) UNSIGNED,
MAX_SALARY DECIMAL(10,2) UNSIGNED 
);
-- DESCRIBE JOBS;
-- ALTER TABLE DEPARTMENTS ADD PRIMARY KEY (DEPARTMENT_ID);
-- ALTER TABLE DEPARTMENTS ADD COLUMN(DEPARTMENT_NAME VARCHAR(20));
-- ALTER TABLE DEPARTMENTS ADD FOREIGN KEY (MANAGER_ID) REFERENCES EMPLOYEES(EMPLOYEE_ID);
-- DESCRIBE DEPARTMENTS;
-- DROP TABLE JOBS;
CREATE TABLE JOB_HISTORY (
EMPLOYEE_ID INT UNSIGNED,
START_DATE 
);